"""Add fast_slow_duration_to_walkingsession

Revision ID: 29550edbacbf
Revises: 85132c2e6fac
Create Date: 2025-05-20 14:36:34.704695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29550edbacbf'
down_revision = '85132c2e6fac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walking_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fast_duration_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('slow_duration_minutes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walking_session', schema=None) as batch_op:
        batch_op.drop_column('slow_duration_minutes')
        batch_op.drop_column('fast_duration_minutes')

    # ### end Alembic commands ###
